kind: ServiceAccount
apiVersion: v1
metadata:
  annotations:
    iam.gke.io/gcp-service-account: sa-for-bucket@myproject.iam.gserviceaccount.com
  name: tfmodules
  namespace: tfmodules
---
# provisionning the service account and the IAM permisisons using config connector
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  annotations:
    cnrm.cloud.google.com/management-conflict-prevention-policy: none
    cnrm.cloud.google.com/project-id: myproject
  name: sa-for-bucket
  namespace: myproject-cc
spec:
  displayName: SA for tfmodules workload identity
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: tfmodules-wi
  namespace: myproject-cc
spec:
  member: "serviceAccount:myproject.svc.id.goog[tfmodules/tfmodules]"
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    external: projects/myproject
    kind: Project
  role: roles/iam.workloadIdentityUser
