name: Publish

on:
  push:
    branches: ["main"]
  pull_request:
    branches: [main]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - uses: actions/checkout@v2

      - uses: imjasonh/setup-ko@v0.4
        env:
          KO_DOCKER_REPO: magicleap/tfmodules
      - env:
          auth_token: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          echo "${auth_token}" | ko login index.docker.io --username magicleapcloud --password-stdin
          ko publish ./cmd/tfmodules --bare
