name: Publish

on:
  push:
    branches: ["main"]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - uses: actions/checkout@v2

      - uses: imjasonh/setup-ko@v0.4
        env:
          KO_DOCKER_REPO: magicleap/tfmodules

      - run: ko publish ./cmd/tfregistry --bare
